# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Discord-bot-deploy

on:
  push:
    branches: [workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: echo ${{secrets.SSHKEY}} > id_rsa
      - run: cat id_rsa
      # - run: ssh -i ${{secrets.SSHKEY}} ${{secrets.USER}}@${{secrets.host}}
      - run: ls
  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Copy repository contents via scp
  #       uses: appleboy/scp-action@master
  #       env:
  #         HOST: ${{ secrets.HOST }}
  #         USERNAME: ${{ secrets.USERNAME }}
  #         PORT: ${{ secrets.PORT }}
  #         KEY: ${{ secrets.SSHKEY }}
  #       with:
  #         source: '.'
  #         target: '/RPG-DEPLY'

  #     - name: Executing remote command
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         USERNAME: ${{ secrets.USERNAME }}
  #         PORT: ${{ secrets.PORT }}
  #         KEY: ${{ secrets.SSHKEY }}
  #         script: ls
#     - run: npm run build --if-present
#     - run: npm test
